require("config.statusline")
require("config.options")
require("config.keymaps")
require("config.commands")
require("config.lsp")
require("config.commands-telescope")
require("config.plugins")
-- require("config.treesitter")
